// <auto-generated />
using System;
using BST;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BST.Backend.Migrations
{
    [DbContext(typeof(BSTDbContext))]
    partial class BSTDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BST.Models.Map", b =>
                {
                    b.Property<Guid>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<string>("BeatSaverId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("beat_saver_id");

                    b.Property<int>("Bpm")
                        .HasColumnType("integer")
                        .HasColumnName("bpm");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<int>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<string>("Mapper")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mapper");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("MapId")
                        .HasName("pk_maps");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_maps_model_id");

                    b.ToTable("maps", (string)null);
                });

            modelBuilder.Entity("BST.Models.MapPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_date");

                    b.HasKey("Id")
                        .HasName("pk_map_pools");

                    b.HasIndex("MapId")
                        .HasDatabaseName("ix_map_pools_map_id");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_map_pools_model_id");

                    b.ToTable("map_pools", (string)null);
                });

            modelBuilder.Entity("BST.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_model");

                    b.ToTable("model", (string)null);
                });

            modelBuilder.Entity("BST.Models.Map", b =>
                {
                    b.HasOne("BST.Models.Model", "Model")
                        .WithMany("Map")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maps_model_model_id");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BST.Models.MapPool", b =>
                {
                    b.HasOne("BST.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_pools_maps_map_id");

                    b.HasOne("BST.Models.Model", "Model")
                        .WithMany("MapPools")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_pools_model_model_id");

                    b.Navigation("Map");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BST.Models.Model", b =>
                {
                    b.Navigation("Map");

                    b.Navigation("MapPools");
                });
#pragma warning restore 612, 618
        }
    }
}
